<a href="https://colab.research.google.com/github/Numanur/data-science-ml/blob/main/Scikit_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
# Standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Colab Datasets/heart-disease.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
#creating x(feature matrix)
x = df.drop("target", axis=1)
#creating y (labels)
y = df["target"]


In [5]:
#choosing a model
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [6]:
#split data into training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [7]:
#training the model
clf.fit(x_train, y_train);

In [8]:
#predicting
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1])

In [9]:
y_test

1      1
242    0
272    0
148    1
100    1
      ..
215    0
229    0
21     1
63     1
130    1
Name: target, Length: 91, dtype: int64

In [10]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.3f}")


Accuracy: 0.802


In [11]:
clf.score(x_train, y_train)

1.0

In [12]:
clf.score(x_test, y_test)

0.8021978021978022

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.79      0.77        38
           1       0.84      0.81      0.83        53

    accuracy                           0.80        91
   macro avg       0.80      0.80      0.80        91
weighted avg       0.80      0.80      0.80        91



In [14]:
confusion_matrix(y_test, y_pred)

array([[30,  8],
       [10, 43]])

In [15]:
accuracy_score(y_test, y_pred)

0.8021978021978022

# **Fine Tuning the model**

In [16]:
#we need to tune the n_estimators
np.random.seed(0)
for i in range(10,100,10):
  print(f"Trying model with {i} estimators...")
  clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
  print(f"Model accuracy on test set: {clf.score(x_test, y_test)*100:.3f}%")
  print("")

Trying model with 10 estimators...
Model accuracy on test set: 76.923%

Trying model with 20 estimators...
Model accuracy on test set: 86.813%

Trying model with 30 estimators...
Model accuracy on test set: 82.418%

Trying model with 40 estimators...
Model accuracy on test set: 82.418%

Trying model with 50 estimators...
Model accuracy on test set: 82.418%

Trying model with 60 estimators...
Model accuracy on test set: 84.615%

Trying model with 70 estimators...
Model accuracy on test set: 84.615%

Trying model with 80 estimators...
Model accuracy on test set: 84.615%

Trying model with 90 estimators...
Model accuracy on test set: 82.418%



In [17]:
import pickle
pickle.dump(clf, open("random_forest_v1.pkl", "wb"))

In [18]:
loaded_model = pickle.load(open("random_forest_v1.pkl", "rb"))
loaded_model.score(x_test, y_test)

0.8241758241758241

# **Finding best Settings**

In [19]:
from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'n_estimators': [100, 200, 300, 400, 500],
    'max_depth': [5, 10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']   # <-- No 'auto' anymore
}


rf_random = RandomizedSearchCV(
    estimator = clf,
    param_distributions = param_grid,
    n_iter = 50,  # How many different combinations to try
    cv = 5,       # 5-fold cross-validation
    verbose = 2,  # How much information to print
    random_state = 42,
    n_jobs = -1   # Use all processors
)

In [20]:
rf_random.fit(x_train, y_train)


Fitting 5 folds for each of 50 candidates, totalling 250 fits


RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(n_estimators=90),
                   n_iter=50, n_jobs=-1,
                   param_distributions={'max_depth': [5, 10, 15, 20, None],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500]},
                   random_state=42, verbose=2)

In [21]:
print(rf_random.best_params_)


{'n_estimators': 100, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 20}


In [22]:
best_clf = RandomForestClassifier(
    n_estimators=500,
    min_samples_split=2,
    min_samples_leaf=4,
    max_features='log2',
    max_depth=5,
    random_state=42
)

In [23]:
best_clf.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, max_features='log2', min_samples_leaf=4,
                       n_estimators=500, random_state=42)

In [27]:
y_pred = best_clf.predict(x_test)

In [29]:
best_clf.score(x_train, y_train)

0.9292452830188679

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.8681318681318682

Confusion Matrix:
 [[31  7]
 [ 5 48]]

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.82      0.84        38
           1       0.87      0.91      0.89        53

    accuracy                           0.87        91
   macro avg       0.87      0.86      0.86        91
weighted avg       0.87      0.87      0.87        91



#**Use of predict_proba() function**

In [31]:
best_clf.predict_proba(x_test)

array([[0.35252171, 0.64747829],
       [0.79125682, 0.20874318],
       [0.45101118, 0.54898882],
       [0.07011976, 0.92988024],
       [0.32996246, 0.67003754],
       [0.60213912, 0.39786088],
       [0.14775225, 0.85224775],
       [0.36896105, 0.63103895],
       [0.25028684, 0.74971316],
       [0.92410347, 0.07589653],
       [0.51177161, 0.48822839],
       [0.22582495, 0.77417505],
       [0.449073  , 0.550927  ],
       [0.59275758, 0.40724242],
       [0.06014261, 0.93985739],
       [0.22539259, 0.77460741],
       [0.77488184, 0.22511816],
       [0.82878727, 0.17121273],
       [0.73645675, 0.26354325],
       [0.906075  , 0.093925  ],
       [0.09953483, 0.90046517],
       [0.84672927, 0.15327073],
       [0.74265869, 0.25734131],
       [0.31289554, 0.68710446],
       [0.2172164 , 0.7827836 ],
       [0.49291728, 0.50708272],
       [0.94687137, 0.05312863],
       [0.07869486, 0.92130514],
       [0.7373217 , 0.2626783 ],
       [0.09668426, 0.90331574],
       [0.