<a href="https://colab.research.google.com/github/Numanur/data-science-ml/blob/main/Scikit_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
# Standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
df = pd.read_csv("/content/drive/MyDrive/Colab Datasets/heart-disease.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [6]:
#creating x(feature matrix)
x = df.drop("target", axis=1)
#creating y (labels)
y = df["target"]


In [7]:
#choosing a model
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [35]:
#split data into training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [36]:
#training the model
clf.fit(x_train, y_train);

In [37]:
#predicting
y_pred = clf.predict(x_test)
y_pred

array([1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0])

In [11]:
y_test

210    0
263    0
166    0
101    1
1      1
      ..
267    0
254    0
197    0
273    0
299    0
Name: target, Length: 61, dtype: int64

In [12]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.3f}")


Accuracy: 0.787


In [38]:
clf.score(x_train, y_train)

1.0

In [14]:
clf.score(x_test, y_test)

0.7868852459016393

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.74      0.77      0.75        26
           1       0.82      0.80      0.81        35

    accuracy                           0.79        61
   macro avg       0.78      0.78      0.78        61
weighted avg       0.79      0.79      0.79        61



In [16]:
confusion_matrix(y_test, y_pred)

array([[20,  6],
       [ 7, 28]])

In [17]:
accuracy_score(y_test, y_pred)

0.7868852459016393

# **Fine Tuning the model**

In [18]:
#we need to tune the n_estimators
np.random.seed(0)
for i in range(10,100,10):
  print(f"Trying model with {i} estimators...")
  clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
  print(f"Model accuracy on test set: {clf.score(x_test, y_test)*100:.3f}%")
  print("")

Trying model with 10 estimators...
Model accuracy on test set: 72.131%

Trying model with 20 estimators...
Model accuracy on test set: 81.967%

Trying model with 30 estimators...
Model accuracy on test set: 81.967%

Trying model with 40 estimators...
Model accuracy on test set: 80.328%

Trying model with 50 estimators...
Model accuracy on test set: 80.328%

Trying model with 60 estimators...
Model accuracy on test set: 78.689%

Trying model with 70 estimators...
Model accuracy on test set: 75.410%

Trying model with 80 estimators...
Model accuracy on test set: 81.967%

Trying model with 90 estimators...
Model accuracy on test set: 78.689%



In [19]:
import pickle
pickle.dump(clf, open("random_forest_v1.pkl", "wb"))

In [21]:
loaded_model = pickle.load(open("random_forest_v1.pkl", "rb"))
loaded_model.score(x_test, y_test)

0.7868852459016393

# **Finding best Settings**

In [41]:
from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'n_estimators': [100, 200, 300, 400, 500],
    'max_depth': [5, 10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']   # <-- No 'auto' anymore
}


rf_random = RandomizedSearchCV(
    estimator = clf,
    param_distributions = param_grid,
    n_iter = 50,  # How many different combinations to try
    cv = 5,       # 5-fold cross-validation
    verbose = 2,  # How much information to print
    random_state = 42,
    n_jobs = -1   # Use all processors
)

In [42]:
rf_random.fit(x_train, y_train)


Fitting 5 folds for each of 50 candidates, totalling 250 fits


RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(n_estimators=90),
                   n_iter=50, n_jobs=-1,
                   param_distributions={'max_depth': [5, 10, 15, 20, None],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500]},
                   random_state=42, verbose=2)

In [43]:
print(rf_random.best_params_)


{'n_estimators': 500, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'log2', 'max_depth': 5}


In [44]:
best_clf = RandomForestClassifier(
    n_estimators=500,
    min_samples_split=2,
    min_samples_leaf=4,
    max_features='log2',
    max_depth=5,
    random_state=42
)

In [45]:
best_clf.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, max_features='log2', min_samples_leaf=4,
                       n_estimators=500, random_state=42)

In [46]:
y_pred = best_clf.predict(x_test)

In [47]:
best_clf.score(x_train, y_train)

0.9339622641509434

In [50]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.7692307692307693

Confusion Matrix:
 [[33  9]
 [12 37]]

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.79      0.76        42
           1       0.80      0.76      0.78        49

    accuracy                           0.77        91
   macro avg       0.77      0.77      0.77        91
weighted avg       0.77      0.77      0.77        91

